ASide:
  - Room: "a-00"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 40
      Y: 192
      Update:
        X: 72
    - Name: "jumpThru"
      ID: 182
      Update:
        X: 40
        Width: 16
     
  - Room: "a-01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
      
  - Room: "a-02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "a-03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
      
  - Room: "a-04"
    Holes:
    - Side: Left
      Idx: 2
      Kind: inout
      HighBound: 109
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 18
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "b-01"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "jumpThru"
      ID: 49243
      Update:
        X: 152
        Width: 8
    - Name: "fgtiles"
      X: 128
      Y: 144
      Update:
        Tile: "7" # Cement
    - Name: "fgtiles"
      X: 136
      Y: 144
      Update:
        Tile: "7" # Cement
      
  - Room: "b-02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Down
      Idx: 1
      Kind: none
      Kind: none
    Tweaks:
    - Name: "jumpThru"
      ID: 84292
      Update:
        X: 64
        Width: 16
    - Name: "fgtiles"
      X: 48
      Y: 528
      Update:
        Tile: "4" # Girder
      
  - Room: "b-03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Up
      Idx: 8
      Kind: none
    - Side: Up
      Idx: 9
      Kind: none
    - Side: Up
      Idx: 10
      Kind: none
    - Side: Up
      Idx: 11
      Kind: none
    - Side: Up
      Idx: 12
      Kind: none
    - Side: Up
      Idx: 13
      Kind: none
    - Side: Up
      Idx: 13
      Kind: none
    - Side: Up
      Idx: 15
      Kind: none
    - Side: Up
      Idx: 16
      Kind: none
    - Side: Up
      Idx: 17
      Kind: none
    - Side: Up
      Idx: 18
      Kind: none
    - Side: Up
      Idx: 19
      Kind: none
    - Side: Up
      Idx: 20
      Kind: none
    - Side: Up
      Idx: 21
      Kind: none
    - Side: Up
      Idx: 22
      Kind: none
    - Side: Up
      Idx: 23
      Kind: none
    - Side: Up
      Idx: 24
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    Tweaks:
    - Name: "exitBlock"
      Update:
        Remove: true
    - Name: "invisibleBarrier"
      Update:
        Remove: true
        
  - Room: "b-04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Up
      Idx: 8
      Kind: none
    - Side: Up
      Idx: 9
      Kind: none
    - Side: Up
      Idx: 10
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
      
  - Room: "b-05"
    Holes:
    - Side: Left
      Idx: 6
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 19
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Left
      Idx: 4
      Kind: none
    - Side: Left
      Idx: 5
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 4
      Kind: none
    - Side: Right
      Idx: 5
      Kind: none
    - Side: Right
      Idx: 6
      Kind: none
    - Side: Right
      Idx: 7
      Kind: none
    - Side: Right
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "c-01"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "jumpThru"
      ID: 26849
      Update:
        X: 64
        Width: 8
    - Name: "fgtiles"
      X: 40
      Y: 160
      Update:
        Tile: "5" # Tower
    - Name: "fgtiles"
      X: 48
      Y: 160
      Update:
        Tile: "5" # Tower
      
  - Room: "c-02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 5
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
      
  - Room: "c-03"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Down
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "jumpThru"
      ID: 52
      Update:
        X: 56
        Width: 16
    - Name: "cameraOffsetTrigger"
      ID: 83
      Update:
        Width: 32
    - Name: "cameraOffsetTrigger"
      Update:
        Add: true
        X: 32
        Y: 744
        Width: 96
        Height: 40
        Values:
          cameraX: 0
          cameraY: 0
      
  - Room: "c-04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "c-05"
    Holes:
    - Side: Left
      Idx: 2
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 19
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "d-01"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: expert
    Tweaks:
    - Name: "jumpThru"
      ID: 66783
      Update:
        Width: 8
    - Name: "fgtiles"
      X: 168
      Y: 152
      Update:
        Tile: "9" # Wood
    - Name: "fgtiles"
      X: 178
      Y: 152
      Update:
        Tile: "9" # Wood
    - ID: 379
      Name: "jumpThru"
      Update:
        Width: 24
    - ID: 308
      Name: "jumpThru"
      Update:
        X: 160
        Width: 24
        
  - Room: "d-02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "d-03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
      
  - Room: "d-04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
      
  - Room: "d-05"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 18
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
      
  - Room: "e-01n"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: two
        Difficulty: expert
      ReqIn:
        Dashes: two
        Difficulty: perfect
    Tweaks:
    - Name: "spawn"
      X: 1352
      Y: 96
      Update:
        X: 1288
    - Name: "jumpThru"
      ID: 4855
      Update:
        X: 152
        Width: 8
    - Name: "fgtiles"
      X: 128
      Y: 152
      Update:
        Tile: "b" # Cliffside
    - Name: "fgtiles"
      X: 136
      Y: 152
      Update:
        Tile: "b" # Cliffside
      
  - Room: "e-02h"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "e-03r"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: perfect
        - Dashes: two
          Difficulty: expert
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "e-04r"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      HighBound: 16
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
      
  - Room: "e-05h"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 19
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "exitBlock"
      Update:
        Remove: true
    - Name: "invisibleBarrier"
      Update:
        Remove: true
      
  - Room: "f-01"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: expert
    Tweaks:
    - Name: "jumpThru
      ID: 36355
      Update: 
        X: 152
        Width: 8
    - Name: "fgtiles"
      X: 144
      Y: 152
      Update:
        Tile: "d" # Temple A
        
  - Room: "f-02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
      
  - Room: "f-03"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "jumpThru"
      ID: 94527
      Update: 
        X: 80
        Width: 8
    - Name: "fgtiles"
      X: 56
      Y: 152
      Update:
        Tile: "d" # Temple A
    - Name: "fgtiles"
      X: 64
      Y: 152
      Update:
        Tile: "d" # Temple A
      
  - Room: "f-04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "f-05"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 19
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 3
      Kind: none
    - Side: Right
      Idx: 4
      Kind: none
    - Side: Right
      Idx: 5
      Kind: none
    - Side: Right
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    Tweaks:
    - Name: "jumpThru"
      ID: 34866
      Update: 
        X: 40
        Width: 16
      
  - Room: "g-01"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 27
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
      
  - Room: "g-02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 9
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    Tweaks:
    - Name: "cameraTargetTrigger" # fix offscreen trigger
      ID: 355
      Update:
        Height: 144
      
  - Room: "g-03"
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      Launch: 606
      ReqOut:
        Dashes: two
        Difficulty: expert
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
      
  - Room: "g-04"
    ReqEnd:
      Dashes: two
      Difficulty: expert
    Holes:
    - Side: Down
      Idx: 0
      Kind: in
      Launch: 19
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none