ASide:
  - Room: "a-00"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
    # blocked
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
        Difficulty: normal
      ReqIn:
        Dashes: zero
        Difficulty: normal
    Subrooms:
    - Room: "up"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
        
  - Room: "a-00s"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: -1
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: zero
          Difficulty: expert
        - Dashes: one
          Difficulty: normal
        
  - Room: "a-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
      
  - Room: "a-02"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: RightToLeft
      ReqOut:
        Dashes: zero
        Difficulty: normal
      ReqIn:
        Dashes: one
        Difficulty: normal
      
  - Room: "a-03"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: RightToLeft
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
      ReqIn:
        Or:
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: normal
      
  - Room: "a-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    ExtraSpace:
    - X: 88
      Y: 184
      Width: 168
      Height: 88
      
  - Room: "b-01"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: RightToLeft
      ReqOut:
        Dashes: zero
        Difficulty: normal
      ReqIn:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 64
        Y: 24
    - Name: "jumpThru"
      Update:
        Add: true
        X: 56
        Y: 24
        Width: 16
    - Name: "spikesUp"
      Update:
        Remove: true
        
  - Room: "b-02"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: 7
    - Side: Left # secret exit
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: out
    # blocked
    - Side: Right
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 64
      Y: 168
      Update:
        Default: true
      
  - Room: "b-03"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Right # secret exit, dash block
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "spikesLeft"
      Update:
        Remove: true
    - Name: "spikesRight"
      Update:
        Remove: true
    - Name: "jumpThru"
      ID: 294
      Update:
        X: 240
        Width: 16
    - Name: "spawn"
      Update:
        Add: true
        X: 40
        Y: 64
    - Name: "jumpThru"
      Update:
        Add: true
        X: 32
        Y: 64
        Width: 16
        
  # b-03s cut (boring straight room)
      
  - Room: "b-04"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: expert
        - Dashes: one
          Difficulty: normal
      ReqIn:
        Dashes: one
        Difficulty: normal
        
  - Room: "b-05"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: zero
        Difficulty: hard
    Tweaks:
    - Name: "exitBlock"
      Update:
        Remove: true
      
  - Room: "b-06"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 1
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: TopToBottom
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: expert
        - Dashes: one
          Difficulty: normal
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
        
  - Room: "b-07"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: RightToLeft
      ReqBoth:
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
    Subrooms:
    - Room: "strange"
      Holes:
      - Side: Left
        Idx: 1
        Kind: unknown
      - Side: Down
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "noRefillTrigger"
      Update:
        Remove: true
      
  - Room: "b-08"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: -1
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "secret"
      ReqOut: # can use pink refill for secret exit
        Dashes: zero
        Difficulty: normal
      ReqIn:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "secret"
      Holes:
      - Side: Right
        Idx: 1
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 144
      Y: 56
      Update:
        Default: true
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
    - Name: "noRefillTrigger"
      Update:
        Remove: true
    - Name: "conditionBlock"
      Update:
        Remove: true
    - Name: "wallBooster" # makes room transition look less weird
      ID: 352
      Update:
        Height: 136
    - Name: "wallBooster"
      ID: 353
      Update:
        Height: 136
    
  - Room: "house"
    End: true
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    # blocked
    - Side: Left # cut some entrances so this ending is chosen less often
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "noRefillTrigger"
      Update:
        Remove: true
    - Name: "spikesUp"
      Update:
        Remove: true
    - Name: "wallBooster" # makes room transition look less weird
      ID: 347
      Update:
        Y: 0
        Height: 104
    - Name: "wallBooster"
      ID: 351
      Update:
        Y: 0
        Height: 48
      
  - Room: "house-b"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: RightToLeft
      ReqOut:
        Dashes: two
        Difficulty: normal
      ReqIn:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "spawn"
      X: 264
      Y: 64
      Update:
        Default: true
          
  - Room: "house-c"
    Hub: true
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: normal
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: normal
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: -1
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
    - Name: "dashBlock"
      ID: 1881
      Update:
        Remove: true
    - Name: "dashBlock"
      ID: 1359
      Update:
        Remove: true
    - Name: "fgTiles"
      X: 45
      Y: 8
      Update:
        Tile: "5" # Tower
    - Name: "fgTiles"
      X: 46
      Y: 8
      Update:
        Tile: "5" # Tower
    - Name: "player"
      X: 752
      Y: 64
      Update:
        Default: true
      
  - Room: "house-d"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: -1
    - Side: Up
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: perfect
        - Dashes: two
          Difficulty: expert
    Tweaks:
    - Name: "fgTiles"
      X: 22
      Y: 30
      Update:
        Tile: "7" # Cement
    - Name: "fgTiles"
      X: 23
      Y: 30
      Update:
        Tile: "7" # Cement
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
          
  - Room: "house-e"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: -1
      ReqOut:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
    - Name: "dashBlock"
      ID: 0
      Update:
        Remove: true
    - Name: "fgTiles"
      X: 43
      Y: 20
      Update:
        Tile: "5" # Tower
    - Name: "fgTiles"
      X: 44
      Y: 20
      Update:
        Tile: "5" # Tower
      
  - Room: "house-f"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      
  # thegate cut, doesn't work well in randomizer
        
  - Room: "bigmirror"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true